package enums;

public enum LogOperation {
	BOOK_FLIGHT, BOOK_COUNT_REQUEST, ADD_FLIGHT, EDIT_FLIGHT, REMOVE_FLIGHT,
	ADD_PASSENGER_RECORD, EDIT_PASSENGER_RECORD, REMOVE_PASSENGER_RECORD, UNKNOWN,
	SOCKET_EXCEPTION, EXCEPTION, REMOTE_EXCEPTION, IO_EXCEPTION, ILLEGAL_ARGUMENT_EXCEPTION,
	LOGIN, BAD_LOGIN, REGISTER_SERVER, UNREGISTER_SERVER, REQUEST_RECEIVED, REQUEST_MADE;
}
