package dfrs;

/**
* dfrs/FlightReservationServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Jerem/Source/Repos/workspace/SOEN423_ASSIGNMENT2_DFRS/src/server/FlightReservationServer.idl
* Tuesday, November 1, 2016 12:30:18 PM EDT
*/

public final class FlightReservationServerHolder implements org.omg.CORBA.portable.Streamable
{
  public dfrs.FlightReservationServer value = null;

  public FlightReservationServerHolder ()
  {
  }

  public FlightReservationServerHolder (dfrs.FlightReservationServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = dfrs.FlightReservationServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    dfrs.FlightReservationServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return dfrs.FlightReservationServerHelper.type ();
  }

}
