package dfrs;


/**
* dfrs/FlightReservationServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Jerem/Source/Repos/workspace/SOEN423_ASSIGNMENT2_DFRS/src/server/FlightReservationServer.idl
* Tuesday, November 1, 2016 12:30:18 PM EDT
*/

public interface FlightReservationServerOperations 
{
  boolean bookFlight (String firstName, String lastName, String Address, String phoneNumber, String flightWithClass);
  String getBookedFlightCount (String flightClassOperation);
  boolean editFlightRecord (String recordOperation, String flightParameter, String newValue);
  boolean transferReservation (String passengerRecordId, String currentCity, String otherCity);
  String[] getFlights ();
  String[] getAvailableFlights ();
  String[] getManagerIds ();
  String[] getPassengerRecords ();
  void serveRequests (float udpPort);
  void registerServer ();
  void unregisterServer ();
  void setOtherServers (String[] otherServers);
} // interface FlightReservationServerOperations
