package dfrs;


/**
* dfrs/FlightReservationServerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Jerem/Source/Repos/workspace/SOEN423_ASSIGNMENT2_DFRS/src/server/FlightReservationServer.idl
* Tuesday, November 1, 2016 12:30:18 PM EDT
*/

public abstract class FlightReservationServerPOA extends org.omg.PortableServer.Servant
 implements dfrs.FlightReservationServerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("bookFlight", new java.lang.Integer (0));
    _methods.put ("getBookedFlightCount", new java.lang.Integer (1));
    _methods.put ("editFlightRecord", new java.lang.Integer (2));
    _methods.put ("transferReservation", new java.lang.Integer (3));
    _methods.put ("getFlights", new java.lang.Integer (4));
    _methods.put ("getAvailableFlights", new java.lang.Integer (5));
    _methods.put ("getManagerIds", new java.lang.Integer (6));
    _methods.put ("getPassengerRecords", new java.lang.Integer (7));
    _methods.put ("serveRequests", new java.lang.Integer (8));
    _methods.put ("registerServer", new java.lang.Integer (9));
    _methods.put ("unregisterServer", new java.lang.Integer (10));
    _methods.put ("setOtherServers", new java.lang.Integer (11));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // dfrs/FlightReservationServer/bookFlight
       {
         String firstName = in.read_string ();
         String lastName = in.read_string ();
         String Address = in.read_string ();
         String phoneNumber = in.read_string ();
         String flightWithClass = in.read_string ();
         boolean $result = false;
         $result = this.bookFlight (firstName, lastName, Address, phoneNumber, flightWithClass);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // dfrs/FlightReservationServer/getBookedFlightCount
       {
         String flightClassOperation = in.read_string ();
         String $result = null;
         $result = this.getBookedFlightCount (flightClassOperation);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // dfrs/FlightReservationServer/editFlightRecord
       {
         String recordOperation = in.read_string ();
         String flightParameter = in.read_string ();
         String newValue = in.read_string ();
         boolean $result = false;
         $result = this.editFlightRecord (recordOperation, flightParameter, newValue);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // dfrs/FlightReservationServer/transferReservation
       {
         String passengerRecordId = in.read_string ();
         String currentCity = in.read_string ();
         String otherCity = in.read_string ();
         boolean $result = false;
         $result = this.transferReservation (passengerRecordId, currentCity, otherCity);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // dfrs/FlightReservationServer/getFlights
       {
         String $result[] = null;
         $result = this.getFlights ();
         out = $rh.createReply();
         dfrs.StringsHelper.write (out, $result);
         break;
       }

       case 5:  // dfrs/FlightReservationServer/getAvailableFlights
       {
         String $result[] = null;
         $result = this.getAvailableFlights ();
         out = $rh.createReply();
         dfrs.StringsHelper.write (out, $result);
         break;
       }

       case 6:  // dfrs/FlightReservationServer/getManagerIds
       {
         String $result[] = null;
         $result = this.getManagerIds ();
         out = $rh.createReply();
         dfrs.StringsHelper.write (out, $result);
         break;
       }

       case 7:  // dfrs/FlightReservationServer/getPassengerRecords
       {
         String $result[] = null;
         $result = this.getPassengerRecords ();
         out = $rh.createReply();
         dfrs.StringsHelper.write (out, $result);
         break;
       }

       case 8:  // dfrs/FlightReservationServer/serveRequests
       {
         float udpPort = in.read_float ();
         this.serveRequests (udpPort);
         out = $rh.createReply();
         break;
       }

       case 9:  // dfrs/FlightReservationServer/registerServer
       {
         this.registerServer ();
         out = $rh.createReply();
         break;
       }

       case 10:  // dfrs/FlightReservationServer/unregisterServer
       {
         this.unregisterServer ();
         out = $rh.createReply();
         break;
       }

       case 11:  // dfrs/FlightReservationServer/setOtherServers
       {
         String otherServers[] = dfrs.StringsHelper.read (in);
         this.setOtherServers (otherServers);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:dfrs/FlightReservationServer:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public FlightReservationServer _this() 
  {
    return FlightReservationServerHelper.narrow(
    super._this_object());
  }

  public FlightReservationServer _this(org.omg.CORBA.ORB orb) 
  {
    return FlightReservationServerHelper.narrow(
    super._this_object(orb));
  }


} // class FlightReservationServerPOA
