package dfrs;


/**
* dfrs/StringsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Jerem/Source/Repos/workspace/SOEN423_ASSIGNMENT2_DFRS/src/server/FlightReservationServer.idl
* Tuesday, November 1, 2016 12:30:18 PM EDT
*/

public final class StringsHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public StringsHolder ()
  {
  }

  public StringsHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = dfrs.StringsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    dfrs.StringsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return dfrs.StringsHelper.type ();
  }

}
