package dfrs;


/**
* dfrs/FlightReservationServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Jerem/Source/Repos/workspace/SOEN423_ASSIGNMENT2_DFRS_V2/src/FlightReservationServer.idl
* Tuesday, November 1, 2016 4:03:12 PM EDT
*/

public interface FlightReservationServerOperations 
{
  boolean bookFlight (String firstName, String lastName, String address, String phoneNumber, String flightIdAndFlightClass);
  String getBookedFlightCount (String managerIdAndFlightClass);
  boolean editFlightRecord (String managerIdAndRecordIdAndDbOperation, String flightParameter, String newValue);
  boolean transferReservation (String passengerRecordId, String currentCity, String otherCity);
  String[] getFlights ();
  String[] getAvailableFlights ();
  String[] getManagerIds ();
  String[] getPassengerRecords ();
} // interface FlightReservationServerOperations
