package dfrs;


/**
* dfrs/FlightReservationServerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Jerem/Source/Repos/workspace/SOEN423_ASSIGNMENT2_DFRS_V2/src/FlightReservationServer.idl
* Tuesday, November 1, 2016 4:03:12 PM EDT
*/

public abstract class FlightReservationServerPOA extends org.omg.PortableServer.Servant
 implements dfrs.FlightReservationServerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("bookFlight", new java.lang.Integer (0));
    _methods.put ("getBookedFlightCount", new java.lang.Integer (1));
    _methods.put ("editFlightRecord", new java.lang.Integer (2));
    _methods.put ("transferReservation", new java.lang.Integer (3));
    _methods.put ("getFlights", new java.lang.Integer (4));
    _methods.put ("getAvailableFlights", new java.lang.Integer (5));
    _methods.put ("getManagerIds", new java.lang.Integer (6));
    _methods.put ("getPassengerRecords", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // dfrs/FlightReservationServer/bookFlight
       {
         String firstName = in.read_string ();
         String lastName = in.read_string ();
         String address = in.read_string ();
         String phoneNumber = in.read_string ();
         String flightIdAndFlightClass = in.read_string ();
         boolean $result = false;
         $result = this.bookFlight (firstName, lastName, address, phoneNumber, flightIdAndFlightClass);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // dfrs/FlightReservationServer/getBookedFlightCount
       {
         String managerIdAndFlightClass = in.read_string ();
         String $result = null;
         $result = this.getBookedFlightCount (managerIdAndFlightClass);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // dfrs/FlightReservationServer/editFlightRecord
       {
         String managerIdAndRecordIdAndDbOperation = in.read_string ();
         String flightParameter = in.read_string ();
         String newValue = in.read_string ();
         boolean $result = false;
         $result = this.editFlightRecord (managerIdAndRecordIdAndDbOperation, flightParameter, newValue);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // dfrs/FlightReservationServer/transferReservation
       {
         String passengerRecordId = in.read_string ();
         String currentCity = in.read_string ();
         String otherCity = in.read_string ();
         boolean $result = false;
         $result = this.transferReservation (passengerRecordId, currentCity, otherCity);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // dfrs/FlightReservationServer/getFlights
       {
         String $result[] = null;
         $result = this.getFlights ();
         out = $rh.createReply();
         dfrs.StringsHelper.write (out, $result);
         break;
       }

       case 5:  // dfrs/FlightReservationServer/getAvailableFlights
       {
         String $result[] = null;
         $result = this.getAvailableFlights ();
         out = $rh.createReply();
         dfrs.StringsHelper.write (out, $result);
         break;
       }

       case 6:  // dfrs/FlightReservationServer/getManagerIds
       {
         String $result[] = null;
         $result = this.getManagerIds ();
         out = $rh.createReply();
         dfrs.StringsHelper.write (out, $result);
         break;
       }

       case 7:  // dfrs/FlightReservationServer/getPassengerRecords
       {
         String $result[] = null;
         $result = this.getPassengerRecords ();
         out = $rh.createReply();
         dfrs.StringsHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:dfrs/FlightReservationServer:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public FlightReservationServer _this() 
  {
    return FlightReservationServerHelper.narrow(
    super._this_object());
  }

  public FlightReservationServer _this(org.omg.CORBA.ORB orb) 
  {
    return FlightReservationServerHelper.narrow(
    super._this_object(orb));
  }


} // class FlightReservationServerPOA
