package dfrs;


/**
* dfrs/FlightReservationServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Jerem/Source/Repos/workspace/SOEN423_ASSIGNMENT2_DFRS_V2/src/FlightReservationServer.idl
* Tuesday, November 1, 2016 4:03:12 PM EDT
*/

public interface FlightReservationServer extends FlightReservationServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FlightReservationServer
