package corba_server;


/**
* corba_server/FlightReservationServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Jerem/Source/Repos/workspace/SOEN423_ASSIGNMENT3_DFRS/src/corba_server/FlightReservationServer.idl
* Friday, November 11, 2016 1:58:05 AM EST
*/

public interface FlightReservationServerOperations 
{
  String bookFlight (String firstName, String lastName, String address, String phoneNumber, String destination, String date, String flightClass);
  String getBookedFlightCount (String bookedFlightCountRequest);
  String editFlightRecord (String editFlightRecordRequest, String fieldToEdit, String newValue);
  String transferReservation (String transferReservationRequest, String currentCity, String otherCity);
  String[] getFlightRecords ();
  String[] getFlightReservations ();
  String[] getPassengerRecords ();
  String[] getManagerRecords ();
} // interface FlightReservationServerOperations
