package corba_server;

/**
* corba_server/FlightReservationServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Jerem/Source/Repos/workspace/SOEN423_ASSIGNMENT3_DFRS/src/corba_server/FlightReservationServer.idl
* Friday, November 11, 2016 1:58:05 AM EST
*/

public final class FlightReservationServerHolder implements org.omg.CORBA.portable.Streamable
{
  public corba_server.FlightReservationServer value = null;

  public FlightReservationServerHolder ()
  {
  }

  public FlightReservationServerHolder (corba_server.FlightReservationServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba_server.FlightReservationServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba_server.FlightReservationServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba_server.FlightReservationServerHelper.type ();
  }

}
