package corba_server;


/**
* corba_server/FlightReservationServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Jerem/Source/Repos/workspace/SOEN423_ASSIGNMENT3_DFRS/src/corba_server/FlightReservationServer.idl
* Friday, November 11, 2016 1:58:05 AM EST
*/

public interface FlightReservationServer extends FlightReservationServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FlightReservationServer
