package corba_server;


/**
* corba_server/stringsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Jerem/Source/Repos/workspace/SOEN423_ASSIGNMENT3_DFRS/src/corba_server/FlightReservationServer.idl
* Friday, November 11, 2016 1:58:05 AM EST
*/

public final class stringsHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public stringsHolder ()
  {
  }

  public stringsHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba_server.stringsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba_server.stringsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba_server.stringsHelper.type ();
  }

}
